// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj7aRjVVRn2ifAg51sTO5zx8kzaMUrRs0',
    appId: '1:122559840661:web:d61da320576e7d6021f69c',
    messagingSenderId: '122559840661',
    projectId: 'bookswap-89462',
    authDomain: 'bookswap-89462.firebaseapp.com',
    storageBucket: 'bookswap-89462.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoi_mznLLxnV701mS_IGhu1zs8nEiGfa0',
    appId: '1:122559840661:android:d51368739fe7005f21f69c',
    messagingSenderId: '122559840661',
    projectId: 'bookswap-89462',
    storageBucket: 'bookswap-89462.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk36iBzTJ18g3rOj0zthz7xAWBNaQrFJo',
    appId: '1:122559840661:ios:3d3e7e1854c6835f21f69c',
    messagingSenderId: '122559840661',
    projectId: 'bookswap-89462',
    storageBucket: 'bookswap-89462.firebasestorage.app',
    iosBundleId: 'com.example.bookSwap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk36iBzTJ18g3rOj0zthz7xAWBNaQrFJo',
    appId: '1:122559840661:ios:3d3e7e1854c6835f21f69c',
    messagingSenderId: '122559840661',
    projectId: 'bookswap-89462',
    storageBucket: 'bookswap-89462.firebasestorage.app',
    iosBundleId: 'com.example.bookSwap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj7aRjVVRn2ifAg51sTO5zx8kzaMUrRs0',
    appId: '1:122559840661:web:9af10b3ce6ad0bcc21f69c',
    messagingSenderId: '122559840661',
    projectId: 'bookswap-89462',
    authDomain: 'bookswap-89462.firebaseapp.com',
    storageBucket: 'bookswap-89462.firebasestorage.app',
  );
}
